### Site Settings ###
title               : Dan Southon
description         : >-                               # >- means to ignore newlines until "url:"
                      Software Engineer | Gamedev<br>
                      Auckland, New Zealand

# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1    # set it as url of an image
google_analytics: dan-southon

BASE_PATH: ""
### about Info ###
about:
  desc              : >-
                      After dabbling in fields such as 3D printing, guitar building,
                      and automotive mechanics/panel beating during highshool, I tried my hand at building games.<br>
                      Since then I decided to pursue a career in software engineering and I’ve never looked back!
### Author Info ###
author:
  name              : Dan Southon
  image             : bc4cc023438561f9a5a22103f160a54f
# behance           : your_username
# dribbble          : your_username
  email             : DMRSouthon@gmail.com
#  facebook          : your_username
  github            : Akavis
# gitlab            : your_username
# instagram         : your_username
  linkedin          : dan-southon-192591154
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : Ak4vis
# vimeo             : your_username
# youtube           : your_channel_name

### Defaults for collections ###
defaults:
  - scope:
      path: "" # empty string for all files
      type: "projects"
    values:
      title: page

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

plugins:
  - jemoji

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock